---
# Tasks specific for RedHat systems

- name: "RedHat | Use EPEL package name"
  set_fact:
    zabbix_agent_package: "zabbix{{ zabbix_short_version }}-agent"
  when:
    - zabbix_repo == "epel"
  tags:
    - zabbix-agent
    - init

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  register: yum_repo_installed
  become: yes
  when:
    zabbix_repo == "zabbix"
  tags:
    - zabbix-agent

- name: "Do a yum clean"
  shell: yum clean all
  when: yum_repo_installed
  tags:
    - skip_ansible_lint

- name: "RedHat | Installing zabbix-agent"
  yum:
    pkg: "{{ item }}"
    state: "{{ zabbix_agent_package_state }}"
  become: yes
  with_items: "{{ zabbix_agent_packages }}"
  tags:
    - init
    - zabbix-agent

- name: "Install policycoreutils-python"
  yum:
    name: policycoreutils-python
    state: installed
  when: zabbix_selinux
  become: yes
  tags:
    - init
    - zabbix-agent

- name: "RedHat | Enable the service"
  service:
    name: "{{ zabbix_agent_service }}"
    enabled: yes
    use: service
  become: yes
  tags:
    - zabbix-agent
    - init
    - service

- name: "Open zabbix-agent port"
  command: firewall-cmd --permanent --add-port=10050/tcp
  tags:
    - zabbix-agent

- name: "Reload firewalld"
  command: firewall-cmd --reload
  tags:
    - zabbix-agent

- name: "Templating userparameter_mysql conf"
  copy:
    src: userparameter_mysql.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart zabbix-agent
  tags:
    - zabbix-agent

