---

- name: "Templating userparameter_mysql conf"
  copy:
    src: userparameter_mysql.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart zabbix-agent
  tags:
    - zabbix-agent

